### ISSUE TITLE
Basic Concepts MVP

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#108]
```[tasklist]
### Tasks
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/102
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/110
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/103
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/104
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/105
```
