### ISSUE TITLE
[User Management] Basic Structure and Tree

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#179]
![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/c3bc21c7-2e1c-40e2-b8ac-8b86efdd3c84)

```[tasklist]
### Tasks
- [x] List all User
- [x] Clone User
- [x] Delete User and User Folder
- [x] Create a new User and Folder
```
