### ISSUE TITLE
Widget manager improvements

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-ui-bundle#195]
[Figma link](https://www.figma.com/file/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?type=design&node-id=270-28730&mode=dev)

```[tasklist]
### Tasks
- [ ] Apply rounding of widgets correctly (Content is creating edgy corners due to overflow)
- [ ] Increase border size for active tabs
- [ ] Apply the right color for sidewidget tab titles
- [ ] Connect inactive tab title background color to a new token
- [ ] Titles of sidewidgets should have a higher top padding
- [ ] Tab titles should only show the hover effect while the tab is inactive
```
