### ISSUE TITLE
Editor improvements

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-ui-bundle#196]
```[tasklist]
### Tasks
- [x] [Toolbars](https://www.figma.com/file/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?type=design&node-id=322-63185&mode=dev) on second level should use a new background-color token
- [x] [Sidebar](https://www.figma.com/file/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?type=design&node-id=318-52087&mode=dev) has a new background-color
- [x] [Sidebar](https://www.figma.com/file/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?type=design&node-id=318-52087&mode=dev) should have a border-left when opened
- [x] [Active tabs](https://www.figma.com/file/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?type=design&node-id=318-52091&mode=dev) in the sidebar have a new highlighting
- [x] Apply padding for [editor tabs](https://www.figma.com/file/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?type=design&node-id=271-69045&mode=dev) correctly
```
