### ISSUE TITLE
Basic Layout POC

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#90]
```[tasklist]
### Tasks
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/92
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/93
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/96
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/97
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/99
- [ ] https://github.com/pimcore/studio-ui-bundle/issues/106
```
